'use strict';
const $=id=>document.getElementById(id);
let busy=false,history=[],attachments=[],currentRole='onboarding',lastAssistantText='',cachedArtifacts=[],cachedDirectives=[],docxTemplateBase64='';
const stageMap={start:['onboarding','Mulai dari nol'],title:['topic_framer','Judul & RQ'],proposal:['method_fit','Proposal'],data:['stats_reviewer','Data & analisis'],writing:['drafting_assistant','Penulisan'],revision:['critic','Revisi pembimbing'],defense:['mock_examiner','Persiapan sidang']};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').hidden=true,3600)}
async function api(path,data){const r=await fetch(path,{method:data!==undefined?'POST':'GET',headers:data!==undefined?{'Content-Type':'application/json'}:{},body:data!==undefined?JSON.stringify(data):undefined});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||`HTTP ${r.status}`);return j}
function md(s){return esc(s).replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h3>$1</h3>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\n/g,'<br>')}
function msg(text,type,meta=''){ $('welcome').hidden=true;const a=document.createElement('article');a.className='message '+type;a.innerHTML=`<div class="avatar">${type==='user'?'ANDA':'ATA'}</div><div><div class="message-head">${type==='user'?'Anda':esc(meta||'ATA')}</div><div class="bubble">${md(text)}</div>${type==='assistant'?'<div class="message-actions"><button data-save>Simpan ke Naskah</button><button data-copy>Salin</button></div>':''}</div>`;if(type==='assistant'){a.querySelector('[data-copy]').onclick=()=>navigator.clipboard?.writeText(text).then(()=>toast('Disalin'));a.querySelector('[data-save]').onclick=()=>saveAssistantArtifact(text)}$('thread').append(a);$('thread').scrollTop=$('thread').scrollHeight;return a}
async function saveAssistantArtifact(text){const title=prompt('Judul artefak / bab','Bab I');if(!title)return;const kind=/^bab\s/i.test(title)?'chapter':'draft';try{const r=await api('/api/artifacts/save',{kind,title,content:text});toast(`Tersimpan sebagai versi ${r.version}`);loadArtifacts()}catch(e){toast(e.message)}}
function openModal(){$('projectModal').hidden=false;$('projectModal').setAttribute('aria-hidden','false');$('pStudent').focus()}function closeModal(){$('projectModal').hidden=true;$('projectModal').setAttribute('aria-hidden','true')}
$('newProject').onclick=openModal;$('closeProjectModal').onclick=closeModal;$('cancelProject').onclick=closeModal;
$('projectForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/projects/create',{student:$('pStudent').value.trim(),program:$('pProgram').value.trim(),topic:$('pTopic').value.trim(),domain:$('pDomain').value,method:$('pMethod').value,advisor:$('pAdvisor').value.trim(),deadline:$('pDeadline').value.trim(),stage:'start'});closeModal();$('projectForm').reset();await refreshAll();toast('Ruang tesis dibuat')}catch(err){toast(err.message)}};
async function loadProjects(){const list=await api('/api/projects');const active=await api('/api/projects/active');$('projectSelect').innerHTML=list.length?list.map(p=>`<option value="${esc(p.id)}" ${p.id===active.id?'selected':''}>${esc(p.name||p.topic)}</option>`).join(''):'<option>Belum ada tesis</option>';if(!list.length){$('nextAction').hidden=true;return}await loadNext()}
$('projectSelect').onchange=async e=>{try{await api('/api/projects/switch',{id:e.target.value});history=[];await refreshAll()}catch(err){toast(err.message)}};
async function loadNext(){try{const n=await api('/api/next-action');$('nextAction').hidden=false;$('nextTitle').textContent=n.label;$('nextReason').textContent=n.reason;$('wbNextTitle').textContent=n.label;$('wbNextReason').textContent=n.reason;$('runNext').dataset.role=n.role;$('goalPill').textContent='Fokus · '+n.label}catch{$('nextAction').hidden=true}}
$('runNext').onclick=()=>{currentRole=$('runNext').dataset.role||'onboarding';$('prompt').value='Bantu saya mengerjakan langkah prioritas ini sekarang. Tanyakan hanya informasi yang benar-benar dibutuhkan.';$('prompt').focus()};
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=async()=>{const stage=b.dataset.stage,[role,label]=stageMap[stage];currentRole=role;$('goalPill').textContent='Mode · '+label;try{await api('/api/projects/update',{stage});await loadNext()}catch(e){if(e.message.includes('Belum ada proyek'))openModal();else toast(e.message)}$('prompt').value=stage==='revision'?'Saya punya arahan/revisi dari pembimbing. Bantu ekstrak arahan yang terukur lalu hubungkan ke naskah yang harus direvisi.':stage==='defense'?'Mulai simulasi sidang dari titik terlemah naskah tesis terbaru saya.':'Bantu saya dari posisi ini dan tentukan langkah paling cepat berikutnya.';$('prompt').focus()});
$('prompt').oninput=()=>{$('prompt').style.height='auto';$('prompt').style.height=Math.min(180,$('prompt').scrollHeight)+'px'};$('prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('chatForm').requestSubmit()}};
$('chatForm').onsubmit=async e=>{e.preventDefault();const text=$('prompt').value.trim();if((!text&&!attachments.length)||busy)return;const outgoing=attachments.map(a=>({filename:a.filename,text:a.text,classification:a.classification,type:a.type}));const displayText=text+(outgoing.length?'\n\n'+outgoing.map(a=>`[LAMPIRAN ${a.filename} · ${a.classification}]`).join('\n'):'');busy=true;$('send').disabled=true;msg(displayText,'user');$('prompt').value='';try{const r=await api('/api/agent/chat',{role:currentRole,message:text,history,attachments:outgoing});if(!r.success)throw Error(r.error||'Model gagal');lastAssistantText=r.content;msg(r.content,'assistant',r.model||'ATA');history.push({role:'user',content:displayText},{role:'assistant',content:r.content});attachments=[];renderAttachments();if(!$('projectSelect').value||$('projectSelect').value.includes('Belum ada'))await loadProjects()}catch(err){msg('Permintaan gagal: '+err.message,'assistant','Sistem');$('prompt').value=text;renderAttachments()}finally{busy=false;$('send').disabled=false}};
$('attachBtn').onclick=()=>$('fileInput').click();
$('fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>20_000_000){toast('Maksimal 20 MB pada mode lokal');return}const classification=$('fileClassification').value;try{const data=await fileToBase64(f);toast(/^audio\//.test(f.type)?'Mentranskrip voice note…':/^image\//.test(f.type)?'Membaca gambar…':'Membaca dokumen…');const p=await api('/api/parse/file',{filename:f.name,base64:data,language:'id',ocr:true,classification});if(!p.success)throw Error(p.error||'Parser gagal');attachments.push({filename:f.name,text:p.text,type:p.type,pending:!!p.media_pending,classification:p.classification||classification,cloud_allowed:p.cloud_allowed!==false});renderAttachments();toast(p.cloud_allowed===false?'Lampiran Rahasia hanya diproses lokal; tidak akan dikirim ke chat cloud.':p.media_pending?`Lampiran masuk: ${p.media_error}`:'Lampiran siap dianalisis')}catch(err){toast(err.message)}e.target.value=''};
async function attachmentToLedger(i){const a=attachments[i];if(!a||!a.text)return;if(a.classification==='confidential')return toast('Lampiran Rahasia tidak boleh dikirim ke AI Ledger.');try{const r=await api('/api/directives/extract',{text:a.text,classification:a.classification,save:true});toast(`${r.saved} arahan pembimbing masuk Ledger`);await Promise.all([loadDirectives(),loadGates()])}catch(e){toast('Ekstraksi arahan gagal: '+e.message)}}
function renderAttachments(){const c=$('attachments');c.hidden=!attachments.length;c.innerHTML=attachments.map((a,i)=>`<span class="attachment-chip">${a.pending?'⚠ ':''}${esc(a.filename)} · ${esc(a.classification||'internal-authorized')} ${a.text?`<button data-ledger="${i}">→ Ledger</button>`:''}<button data-remove="${i}">×</button></span>`).join('');c.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{attachments.splice(+b.dataset.remove,1);renderAttachments()});c.querySelectorAll('[data-ledger]').forEach(b=>b.onclick=()=>attachmentToLedger(+b.dataset.ledger))}
function updateWbState(){const isOpen=window.innerWidth<=1100?$('app').classList.contains('wb-open'):!$('app').classList.contains('wb-closed');$('toggleWorkbench').classList.toggle('active',isOpen);$('toggleWorkbench').setAttribute('aria-expanded',String(isOpen))}
function tab(name){document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==`panel-${name}`);document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===name)));if(window.innerWidth<=1100)$('app').classList.add('wb-open');else $('app').classList.remove('wb-closed');updateWbState()}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('toggleWorkbench').onclick=()=>{if(window.innerWidth<=1100)$('app').classList.toggle('wb-open');else $('app').classList.toggle('wb-closed');updateWbState()};$('closeWorkbench').onclick=()=>{$('app').classList.remove('wb-open');$('app').classList.add('wb-closed');updateWbState()};updateWbState();
async function loadGates(){try{const gs=await api('/api/gates');$('gateList').innerHTML=gs.map(g=>`<div class="item"><div class="item-top"><span>${esc(g.gate)} · ${esc(g.name)}</span><span>${g.passed?'LOLOS':g.progress+'%'}</span></div><div class="gatebar"><i style="width:${g.progress}%"></i></div><p>${Object.entries(g.checks).map(([k,v])=>(v?'✓ ':'○ ')+esc(k)).join('<br>')}</p></div>`).join('');const done=gs.filter(g=>g.passed).length;$('progressValue').textContent=Math.round(done/gs.length*100)+'%';$('progressText').textContent=`${done}/${gs.length} quality gate lolos`}catch{$('gateList').innerHTML='<p class="muted">Belum ada proyek aktif.</p>'}}
async function loadDirectives(){try{cachedDirectives=await api('/api/directives');$('directiveList').innerHTML=cachedDirectives.length?cachedDirectives.map(d=>`<div class="item" data-id="${esc(d.id)}"><div class="item-top"><span class="badge ${d.priority==='MUST'?'must':''}">${esc(d.priority)}</span><span>${esc(d.status)}</span></div><h4>${esc(d.id)} · ${esc(d.directive)}</h4><p>${esc(d.quote||'')}</p><div class="item-actions"><button data-status="addressed">Tandai selesai</button><button data-status="open">Buka lagi</button></div></div>`).join(''):'<p class="muted">Belum ada arahan tersimpan.</p>';$('directiveList').querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{const card=b.closest('[data-id]');await api('/api/directives/update',{id:card.dataset.id,status:b.dataset.status});loadDirectives();loadGates()});fillRevisionSelectors()}catch{$('directiveList').innerHTML='<p class="muted">Belum ada proyek aktif.</p>'}}
$('importDirectives').onclick=async()=>{try{const x=JSON.parse($('directiveJson').value);const r=await api('/api/directives/import',{directives:x});toast(`${r.count} arahan diimport`);$('directiveJson').value='';loadDirectives();loadGates()}catch(e){toast('JSON/Import gagal: '+e.message)}};
$('extractDirectives').onclick=async()=>{const text=$('supervisorText').value.trim();if(!text)return toast('Tempel transkrip/catatan pembimbing dulu');$('extractDirectives').disabled=true;try{const r=await api('/api/directives/extract',{text,classification:$('directiveClassification').value,save:true});$('directiveExtractResult').textContent=JSON.stringify(r.directives,null,2);toast(`${r.saved} arahan masuk Ledger`);await Promise.all([loadDirectives(),loadGates()])}catch(e){$('directiveExtractResult').textContent=e.message;toast(e.message)}finally{$('extractDirectives').disabled=false}};
function fillRevisionSelectors(){$('revisionDirective').innerHTML='<option value="">Tanpa directive khusus</option>'+cachedDirectives.filter(d=>d.status!=='addressed').map(d=>`<option value="${esc(d.id)}">${esc(d.id)} · ${esc(d.directive)}</option>`).join('');$('revisionArtifact').innerHTML=cachedArtifacts.map(a=>`<option value="${esc(a.id)}">${esc(a.title)} · v${a.version}</option>`).join('')}
$('proposeRevision').onclick=async()=>{const artifact_id=$('revisionArtifact').value,directive_id=$('revisionDirective').value;if(!artifact_id)return toast('Simpan naskah dulu');$('proposeRevision').disabled=true;try{const r=await api('/api/revisions/propose',{artifact_id,directive_id});toast('Usulan revisi siap. Belum diterapkan sebelum Anda Accept.');await loadRevisions()}catch(e){toast(e.message)}finally{$('proposeRevision').disabled=false}};
async function loadRevisions(){try{const rows=await api('/api/revisions');$('revisionList').innerHTML=rows.length?rows.map(r=>`<div class="item" data-rev="${esc(r.id)}"><div class="item-top"><span>${esc(r.target_title||'Naskah')}</span><span>${esc(r.status)}</span></div><p>${esc(r.rationale||'')}</p><pre class="revision-diff">${esc(r.diff||'')}</pre>${r.status==='proposed'?'<div class="item-actions"><button data-decision="accept">Accept → versi baru</button><button data-decision="reject">Reject</button></div>':''}</div>`).join(''):'<p class="muted">Belum ada usulan revisi.</p>';$('revisionList').querySelectorAll('[data-decision]').forEach(b=>b.onclick=async()=>{const id=b.closest('[data-rev]').dataset.rev;await api('/api/revisions/decision',{id,decision:b.dataset.decision});toast(b.dataset.decision==='accept'?'Revisi diterapkan sebagai versi baru':'Usulan ditolak');await Promise.all([loadRevisions(),loadArtifacts(),loadDirectives(),loadGates()])})}catch{$('revisionList').innerHTML='<p class="muted">Belum ada proyek aktif.</p>'}}
$('sourceSearch').onsubmit=async e=>{e.preventDefault();const q=$('sourceQuery').value.trim();if(q.length<3)return;$('sourceResults').innerHTML='<p class="muted">Mencari OpenAlex + Crossref…</p>';try{const r=await api('/api/literature/search',{query:q,limit:8});$('sourceResults').innerHTML=r.results.length?r.results.map((s,i)=>`<div class="item"><div class="item-top"><span>${esc(s.year||'—')}</span><span class="badge">KANDIDAT</span></div><h4>${esc(s.title)}</h4><p>${esc((s.authors||[]).slice(0,3).join(', '))}${s.doi?'<br>DOI '+esc(s.doi):''}</p><div class="item-actions"><button data-save-source="${i}">Simpan kandidat</button></div></div>`).join(''):'<p class="muted">Tidak ada hasil.</p>';$('sourceResults').querySelectorAll('[data-save-source]').forEach(b=>b.onclick=async()=>{await api('/api/literature/save',{source:r.results[+b.dataset.saveSource]});toast('Kandidat tersimpan');loadSources()})}catch(err){$('sourceResults').innerHTML='<p class="muted">'+esc(err.message)+'</p>'}};
$('addManualSource').onclick=async()=>{const title=prompt('Judul sumber / regulasi / buku');if(!title)return;const url=prompt('URL resmi (opsional)','')||'';const type=prompt('Jenis sumber','regulation')||'document';const yearRaw=prompt('Tahun (opsional)','')||'';const year=yearRaw&&/^\d{4}$/.test(yearRaw)?Number(yearRaw):null;try{await api('/api/literature/save',{source:{type,title,url,year,authors:[]}});toast('Sumber manual tersimpan sebagai kandidat. Upload dokumen untuk memverifikasi evidence.');loadSources()}catch(e){toast(e.message)}};
async function fileToBase64(f){return await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(f)})}
async function chooseSourceDocument(){return await new Promise(resolve=>{const input=document.createElement('input');input.type='file';input.accept='.pdf,.docx,.txt,.md,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain';input.onchange=()=>resolve(input.files?.[0]||null);input.click()})}
async function loadSources(){
  try{
    const s=await api('/api/sources');
    $('savedSources').innerHTML=s.length?s.map(x=>`<div class="item" data-source="${esc(x.id)}"><div class="item-top"><span>${esc(x.year||'—')}</span><span class="badge ${x.verified?'ok':''}">${x.verified?'VERIFIED':'CANDIDATE'}</span></div><h4>${esc(x.title)}</h4><p>${esc((x.authors||[]).slice(0,3).join(', '))}${x.doi?'<br>'+esc(x.doi):''}</p><div class="item-actions">${!x.verified&&x.doi?'<button data-verify>Verifikasi DOI</button>':''}<button data-brief>Buat Research Brief</button><button data-verify-evidence>Verifikasi evidence dari file</button><button data-add-evidence>Tambah manual</button></div>${x.brief_json?'<p class="muted">Research Brief tersimpan.</p>':''}</div>`).join(''):'<p class="muted">Belum ada sumber.</p>';
    $('savedSources').querySelectorAll('[data-verify]').forEach(b=>b.onclick=async()=>{const id=b.closest('[data-source]').dataset.source;const r=await api('/api/literature/verify',{source_id:id});toast(r.success?'DOI terverifikasi':'DOI tidak valid');loadSources()});
    $('savedSources').querySelectorAll('[data-add-evidence]').forEach(b=>b.onclick=async()=>{const id=b.closest('[data-source]').dataset.source;const locator=prompt('Locator bukti','hal. 12');if(!locator)return;const text=prompt('Potongan bukti persis dari sumber');if(!text)return;const r=await api('/api/evidence/save',{source_id:id,locator,text});toast(r.verification_status==='verified'?'Evidence verified':'Evidence manual tersimpan sebagai UNVERIFIED')});
    $('savedSources').querySelectorAll('[data-brief]').forEach(b=>b.onclick=async()=>{const id=b.closest('[data-source]').dataset.source;const f=await chooseSourceDocument();if(!f)return;if(f.size>20_000_000)return toast('Dokumen sumber maksimal 20 MB');try{toast('Membuat Research Brief + memverifikasi quote…');const source_document_base64=await fileToBase64(f);const r=await api('/api/research-brief/create',{source_id:id,source_filename:f.name,source_document_base64,classification:$('fileClassification').value});toast(`Brief tersimpan · ${r.verified_evidence_count} evidence verified · ${r.rejected_quote_count} quote ditolak`);loadSources()}catch(e){toast('Research Brief gagal: '+e.message)}});
    $('savedSources').querySelectorAll('[data-verify-evidence]').forEach(b=>b.onclick=async()=>{
      const id=b.closest('[data-source]').dataset.source;const f=await chooseSourceDocument();if(!f)return;if(f.size>20_000_000)return toast('Dokumen sumber maksimal 20 MB pada mode lokal');
      const locator=prompt('Locator halaman yang harus cocok','hal. 12');if(!locator)return;const text=prompt('Salin potongan bukti persis dari halaman tersebut');if(!text)return;
      try{toast('Memverifikasi quote terhadap dokumen…');const source_document_base64=await fileToBase64(f);const r=await api('/api/evidence/save',{source_id:id,locator,text,source_filename:f.name,source_document_base64});toast(r.verification_status==='verified'?'Evidence VERIFIED terhadap dokumen':'Evidence belum terverifikasi')}
      catch(e){toast('Verifikasi evidence gagal: '+e.message)}
    });
  }catch{$('savedSources').innerHTML='<p class="muted">Belum ada proyek aktif.</p>'}
}
$('resolveEvidence').onclick=async()=>{const text=$('evidenceText').value.trim();if(!text)return;try{const r=await api('/api/evidence/resolve',{text});$('evidenceResult').textContent=JSON.stringify({verified_score:r.compliance.verified_score,sentences:r.sentences.map(s=>({status:s.status,text:s.text,resolved:s.resolved}))},null,2)}catch(e){$('evidenceResult').textContent=e.message}};
async function loadArtifacts(){try{cachedArtifacts=await api('/api/artifacts');$('artifactList').innerHTML=cachedArtifacts.length?cachedArtifacts.map(x=>`<div class="item"><div class="item-top"><span>${esc(x.kind)}</span><span>v${x.version}</span></div><h4>${esc(x.title)}</h4><p>${esc((x.content||'').slice(0,180))}${(x.content||'').length>180?'…':''}</p></div>`).join(''):'<p class="muted">Belum ada naskah tersimpan.</p>';fillRevisionSelectors()}catch{$('artifactList').innerHTML='<p class="muted">Belum ada proyek aktif.</p>'}}
$('chooseDocxTemplate').onclick=()=>$('docxTemplateInput').click();
$('docxTemplateInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{docxTemplateBase64=await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(f)});$('docxTemplateName').textContent=f.name;toast('Template kampus siap dipakai saat export')}catch(err){toast('Gagal membaca template: '+err.message)}e.target.value=''};
$('exportBibtex').onclick=async()=>{try{const r=await api('/api/references/export-bibtex',{});const bytes=Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0));const blob=new Blob([bytes],{type:r.mime});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=r.filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`BibTeX dibuat dari ${r.source_count} sumber yang benar-benar dirujuk`)}catch(e){toast(e.message)}};
$('exportDocx').onclick=async()=>{try{const r=await api('/api/artifacts/export-docx',{template_base64:docxTemplateBase64||undefined});const bytes=Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0));const blob=new Blob([bytes],{type:r.mime});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=r.filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('DOCX dibuat dari versi naskah terbaru')}catch(e){toast(e.message)}};
$('startDefense').onclick=()=>{currentRole='mock_examiner';$('goalPill').textContent='Mode · Sidang';$('prompt').value='Mulai simulasi sidang. Baca naskah terbaru saya lalu ajukan SATU pertanyaan paling tajam. Jangan beri jawaban dulu.';$('prompt').focus()};
$('weaknessMap').onclick=async()=>{try{$('weaknessResult').textContent='Menganalisis naskah…';const r=await api('/api/defense/weakness-map',{});$('weaknessResult').textContent=r.content||r.error||'Tidak ada hasil'}catch(e){$('weaknessResult').textContent=e.message}};
$('evaluateDefense').onclick=async()=>{const question=$('defenseQuestion').value.trim(),answer=$('defenseAnswer').value.trim();if(!question||!answer)return toast('Isi pertanyaan dan jawaban');$('evaluateDefense').disabled=true;try{const r=await api('/api/defense/evaluate',{question,answer});$('defenseResult').innerHTML=`<div class="score-big">${r.score}/4</div><strong>${esc(r.weakness)}</strong><p>${esc(r.feedback)}</p><p><b>Kerangka jawaban:</b> ${esc(r.ideal_answer)}</p>`;loadDefense()}catch(e){$('defenseResult').textContent=e.message}finally{$('evaluateDefense').disabled=false}};
async function loadDefense(){try{const r=await api('/api/defense/history');const s=r.summary;$('defenseHistory').innerHTML=`<div class="item"><div class="item-top"><span>${s.attempts} latihan</span><span>Rata-rata ${s.average_score}/4</span></div><p>Jawaban defensible (≥3): ${s.ready_ratio}%</p></div>`+r.records.slice(0,8).map(x=>`<div class="item"><div class="item-top"><span>${esc(x.weakness||'umum')}</span><span>${x.score}/4</span></div><h4>${esc(x.question)}</h4><p>${esc(x.feedback||'')}</p></div>`).join('')}catch{$('defenseHistory').innerHTML='<p class="muted">Belum ada histori sidang.</p>'}}
async function saveGateAssessment(gate,data){await api('/api/gates/assessment',{gate,data});toast(`${gate} tersimpan`);await Promise.all([loadGates(),loadNext()])}
$('saveG1').onclick=()=>saveGateAssessment('G1',{finer_scores:{Feasible:+$('g1Feasible').value,Interesting:+$('g1Interesting').value,Novel:+$('g1Novel').value,Ethical:+$('g1Ethical').value,Relevant:+$('g1Relevant').value},supervisor_approved:$('g1Approved').checked}).catch(e=>toast(e.message));
$('saveG2').onclick=()=>saveGateAssessment('G2',{research_gap_ready:$('g2Gap').checked,framework_ready:$('g2Framework').checked,min_sources:+$('g2Min').value,recent_ratio_target:+$('g2Recent').value/100}).catch(e=>toast(e.message));
$('saveG3').onclick=()=>saveGateAssessment('G3',{instrument_ready:$('g3Instrument').checked,analysis_plan_locked:$('g3Plan').checked,proposal_approved:$('g3Approved').checked}).catch(e=>toast(e.message));
$('saveG4').onclick=()=>{try{const data=JSON.parse($('g4Json').value||'{}');saveGateAssessment('G4',data).catch(e=>toast(e.message))}catch(e){toast('JSON G4 tidak valid')}};
$('saveG5').onclick=()=>saveGateAssessment('G5',{similarity:+$('g5Similarity').value,similarity_threshold:+$('g5Threshold').value,open_red_critiques:+$('g5Red').value}).catch(e=>toast(e.message));
$('saveConsistency').onclick=async()=>{try{const rows=JSON.parse($('consistencyJson').value||'[]');const r=await api('/api/consistency/save',{rows});$('consistencyResult').textContent=JSON.stringify(r.rows,null,2);toast(`${r.count} baris matriks disimpan`);loadGates()}catch(e){$('consistencyResult').textContent=e.message;toast('Matriks gagal: '+e.message)}};
async function loadPreflight(){try{const r=await api('/api/preflight');const passed=(r.checks||[]).filter(x=>x.ok).length,total=(r.checks||[]).length;$('preflightStatus').textContent=`Kode ${r.code_ready?'siap':'belum siap'} · ${passed}/${total} check lokal OK · tersisa live test OpenRouter/DB/UAT.`}catch(e){$('preflightStatus').textContent='Preflight gagal: '+e.message}}
async function loadStatus(){try{const s=await api('/api/status');$('topStatus').innerHTML=`<span class="dot"></span> ${s.storage.ephemeral?'Mode demo · storage sementara':'Storage persisten'}`;if(s.storage.warning){$('storageWarning').hidden=false;$('storageWarning').textContent=s.storage.warning}else $('storageWarning').hidden=true}catch{}}
async function refreshAll(){await Promise.allSettled([loadProjects(),loadGates(),loadDirectives(),loadSources(),loadArtifacts(),loadRevisions(),loadDefense(),loadStatus(),loadPreflight()])}
refreshAll();
